#!/usr/bin/env bash
#saved pid, loops infinit traps a few signals and deletes pid file
trap "echo Y U no love me?!; exit" SIGINT
trap "echo I hate the kill command; rm /var/run/holbertonscript.pid; exit" SIGTERM SIGQUIT
echo $$ > /var/run/holbertonscript.pid
while true; do
    echo "To infinity and beyond"
done 
